version: '3'

services:
  node:
    image: node:16.14
    container_name: trybecar
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - database
    ports:
      - 3001:3001
    env_file:
      - .env
  
  database:
    image: mysql:8.0.29
    container_name: trybecar_db
    env_file:
      - .env
    ports:
      - 33060:3306
    volumes:
      - ./:/docker-entrypoint-initdb.d