version: '3'
services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: trybecash_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    depends_on:
      - "database"

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - .env
    volumes:
        - ./trybecash_script.sql:/docker-entrypoint-initdb.d/trybecash_script.sql